//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HLR.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class mahlr
    {
        public long id { get; set; }
        public string msisdncountrycode { get; set; }
        public string msisdn { get; set; }
        public string statuscode { get; set; }
        public Nullable<int> hlrerrorcodeid { get; set; }
        public string subscriberstatus { get; set; }
        public string imsi { get; set; }
        public string mccmnc { get; set; }
        public string mcc { get; set; }
        public string mnc { get; set; }
        public string msin { get; set; }
        public string servingmsc { get; set; }
        public string servinghlr { get; set; }
        public string originalnetworkname { get; set; }
        public string originalcountryname { get; set; }
        public string originalcountrycode { get; set; }
        public string originalcountryprefix { get; set; }
        public string originalnetworkprefix { get; set; }
        public string roamingnetworkname { get; set; }
        public string roamingcountryname { get; set; }
        public string roamingcountrycode { get; set; }
        public string roamingcountryprefix { get; set; }
        public string roamingnetworkprefix { get; set; }
        public string portednetworkname { get; set; }
        public string portedcountryname { get; set; }
        public string portedcountrycode { get; set; }
        public string portedcountryprefix { get; set; }
        public string portednetworkprefix { get; set; }
        public string isvalid { get; set; }
        public string isroaming { get; set; }
        public string isported { get; set; }
        public string usercharge { get; set; }
        public string inserttime { get; set; }
        public string storage { get; set; }
        public string route { get; set; }
        public string Interface { get; set; }
        public Nullable<double> latitud { get; set; }
        public Nullable<double> longitud { get; set; }
        public Nullable<double> cellid { get; set; }
        public Nullable<double> lac { get; set; }
        public Nullable<System.DateTime> fInis { get; set; }
    }
}
