<?xml version="1.0" encoding="utf-8"?><Database Name="GSMPI" Class="GSMPIDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=GSMPI;Persist Security Info=True;User ID=sa;Connect Timeout=5;ConnectRetryCount=3;ConnectRetryInterval=5" SettingsObjectName="GSMApplication.Properties.Settings" SettingsPropertyName="GSMPIConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.caCommands" Member="caCommands">
    <Type Name="caCommands">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="command" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="fIns" AutoSync="Never" Type="System.DateTime" DbType="DateTime NOT NULL" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fAct" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="caCommands_reCommandsParameters" Member="reCommandsParameters" ThisKey="id" OtherKey="idCommand" Type="reCommandsParameters" />
    </Type>
  </Table>
  <Table Name="dbo.reCommandsParameters" Member="reCommandsParameters">
    <Type Name="reCommandsParameters">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tag" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="idCommand" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idParameter" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fIns" AutoSync="Never" Type="System.DateTime" DbType="DateTime NOT NULL" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fAct" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="caCommands_reCommandsParameters" Member="caCommands" ThisKey="idCommand" OtherKey="id" Type="caCommands" IsForeignKey="true" />
      <Association Name="caParameters_reCommandsParameters" Member="caParameters" ThisKey="idParameter" OtherKey="id" Type="caParameters" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.caParameters" Member="caParameters">
    <Type Name="caParameters">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="parameter" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="fIns" AutoSync="Never" Type="System.DateTime" DbType="DateTime NOT NULL" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fAct" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="caParameters_reCommandsParameters" Member="reCommandsParameters" ThisKey="id" OtherKey="idParameter" Type="reCommandsParameters" />
    </Type>
  </Table>
</Database>