//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CellTrack.Models.DataBases
{
    using System;
    using System.Collections.Generic;
    
    public partial class causuarios
    {
        public causuarios()
        {
            this.reusuariosperfil = new HashSet<reusuariosperfil>();
        }
    
        public int id { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public string Nombres { get; set; }
        public Nullable<int> idDetalle { get; set; }
        public System.DateTime fIns { get; set; }
        public Nullable<System.DateTime> fAct { get; set; }
        public string usuario { get; set; }
        public string contrasenia { get; set; }
    
        public virtual ICollection<reusuariosperfil> reusuariosperfil { get; set; }
    }
}
