//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CellTrack.Models.DataBases
{
    using System;
    using System.Collections.Generic;
    
    public partial class demalocalizationsagenda
    {
        public demalocalizationsagenda()
        {
            this.malocalizations = new HashSet<malocalizations>();
        }
    
        public int id { get; set; }
        public bool from { get; set; }
        public bool to { get; set; }
        public Nullable<bool> frecuency { get; set; }
        public System.DateTime fIns { get; set; }
        public Nullable<System.DateTime> fAct { get; set; }
    
        public virtual ICollection<malocalizations> malocalizations { get; set; }
    }
}
