//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CellTrack.Models.DataBases
{
    using System;
    using System.Collections.Generic;
    
    public partial class malocalizations
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string asunto { get; set; }
        public string objetivo { get; set; }
        public int idNotification { get; set; }
        public int idCarrier { get; set; }
        public Nullable<int> idAgenda { get; set; }
        public System.DateTime fIns { get; set; }
        public System.DateTime fAct { get; set; }
    
        public virtual cacarriers cacarriers { get; set; }
        public virtual causuarios causuarios { get; set; }
        public virtual demalocalizationsagenda demalocalizationsagenda { get; set; }
    }
}
