//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CellTrack.Models.DataBases
{
    using System;
    using System.Collections.Generic;
    
    public partial class malocalizations
    {
        public malocalizations()
        {
            this.mahlr = new HashSet<mahlr>();
            this.mapdu = new HashSet<mapdu>();
        }
    
        public int id { get; set; }
        public int idUser { get; set; }
        public string nombre { get; set; }
        public string asunto { get; set; }
        public string objetivo { get; set; }
        public int idNotification { get; set; }
        public int idCarrier { get; set; }
        public Nullable<short> agendaDe { get; set; }
        public Nullable<short> agendaA { get; set; }
        public Nullable<short> agendaFrecuencia { get; set; }
        public System.DateTime fIns { get; set; }
        public Nullable<System.DateTime> fAct { get; set; }
        public bool active { get; set; }
        public bool isDeleted { get; set; }
    
        public virtual cacarriers cacarriers { get; set; }
        public virtual causuarios causuarios { get; set; }
        public virtual causuarios causuarios1 { get; set; }
        public virtual ICollection<mahlr> mahlr { get; set; }
        public virtual ICollection<mapdu> mapdu { get; set; }
    }
}
