//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CellTrack.Models.DataBases
{
    using System;
    using System.Collections.Generic;
    
    public partial class mapdu
    {
        public int id { get; set; }
        public string tipo { get; set; }
        public int idDetalle { get; set; }
        public int idLocalizations { get; set; }
        public System.DateTime fIns { get; set; }
        public bool toNotify { get; set; }
    
        public virtual desmsrecibidos desmsrecibidos { get; set; }
        public virtual malocalizations malocalizations { get; set; }
    }
}
